import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface CompanySettings {
  company_name: string;
  address: string;
  email: string;
  phone: string;
  currency_symbol: string;
}

interface SaleItem {
  product_name: string;
  quantity: number;
  unit_price: number;
  total_price: number;
}

interface Sale {
  id: string;
  customer_name: string;
  issuer_name: string;
  total_amount: number;
  created_at: string;
  items: SaleItem[];
}

export function generateAndDownloadReceiptPDF(
  sale: Sale,
  companySettings: CompanySettings
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header: Centered company details
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(companySettings.company_name, pageWidth / 2, 20, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(companySettings.address, pageWidth / 2, 28, { align: 'center' });
  doc.text(
    `Email: ${companySettings.email} | Phone: ${companySettings.phone}`,
    pageWidth / 2,
    34,
    { align: 'center' }
  );

  doc.setLineWidth(0.5);
  doc.line(10, 40, pageWidth - 10, 40);

  // Invoice details
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('INVOICE', 10, 50);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Invoice ID: ${sale.id.substring(0, 8).toUpperCase()}`, 10, 58);
  doc.text(
    `Date: ${format(new Date(sale.created_at), 'dd MMMM yyyy, hh:mm a')}`,
    10,
    64
  );
  doc.text(`Customer: ${sale.customer_name}`, 10, 70);
  doc.text(`Issued by: ${sale.issuer_name}`, 10, 76);

  // Table of items
  const tableData = sale.items.map((item) => [
    item.quantity,
    item.product_name,
    `${companySettings.currency_symbol}${item.unit_price.toFixed(2)}`,
    `${companySettings.currency_symbol}${item.total_price.toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 85,
    head: [['Qty', 'Item Name', 'Unit Price', 'Total']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [59, 130, 246], // Blue header to match the image
      textColor: 255,
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 80 },
      2: { cellWidth: 40, halign: 'right' },
      3: { cellWidth: 40, halign: 'right' },
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 85;

  // Grand Total
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(
    `Grand Total: ${companySettings.currency_symbol}${sale.total_amount.toFixed(2)}`,
    pageWidth / 2,
    finalY + 10,
    { align: 'center' }
  );

  doc.setLineWidth(0.5);
  doc.line(10, finalY + 15, pageWidth - 10, finalY + 15);

  // Footer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.text('Thank you for your purchase!', pageWidth / 2, finalY + 25, {
    align: 'center',
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(
    `Generated by: ${sale.issuer_name}`,
    pageWidth / 2,
    finalY + 32,
    { align: 'center' }
  );

  // Trigger download
  doc.save(`Invoice_${sale.id.substring(0, 8).toUpperCase()}.pdf`);
}

// Example usage (uncomment to test)
// const sampleSale: Sale = {
//   id: 'e3434a86',
//   customer_name: 'YARO',
//   issuer_name: 'SAIDU USMAN',
//   total_amount: 217000.00,
//   created_at: '2025-10-12T09:37:00Z',
//   items: [
//     { product_name: 'Network Switch 8-Port', quantity: 2, unit_price: 25000.00, total_price: 50000.00 },
//     { product_name: 'Networking Cable', quantity: 4, unit_price: 5000.00, total_price: 20000.00 },
//     { product_name: 'Router Configuration', quantity: 3, unit_price: 15000.00, total_price: 45000.00 },
//     { product_name: 'Technical Support', quantity: 4, unit_price: 8000.00, total_price: 32000.00 },
//     { product_name: 'WiFi Access Point', quantity: 2, unit_price: 35000.00, total_price: 70000.00 },
//   ],
// };
//
// const sampleCompanySettings: CompanySettings = {
//   company_name: 'YAROTECH NETWORK LIMITED',
//   address: 'No. 122 Lukoro Plaza, Farm Center, Kano State',
//   email: 'info@yarotech.com.ng',
//   phone: '+234 814 024 4774',
//   currency_symbol: '₦',
// };
//
// generateAndDownloadReceiptPDF(sampleSale, sampleCompanySettings);